ALTER TABLE users
    ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS locked BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE users
SET enabled = TRUE
WHERE enabled IS NULL;

UPDATE users
SET locked = FALSE
WHERE locked IS NULL;
